server:
  port: 9191

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/E-Learning/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/E-Learning

connection:
  timeout: 3000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"