server:
  port: 8081

spring:
  application:
    name: user-service
  jpa:
    open-in-view: false
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/E-Learning/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/E-Learning

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

keycloak:
  server-url: http://localhost:8080
  realm-name: E-Learning
  admin-cli-client-id: admin-cli
  admin-cli-client-secret: YcF3v6mCsHdNKPveKS8XzYX5wCXMaI6Z